CREATE TABLE IF NOT EXISTS dependentes(
id INT PRIMARY KEY AUTO_INCREMENT,
nomecompleto VARCHAR(100) NOT NULL,
cpf VARCHAR(25) NOT NULL,
rg VARCHAR(15) NOT NULL,
datadenascimento DATE,
genero VARCHAR(40) NOT NULL,
parentesco VARCHAR(30) NOT NULL

);