CREATE TABLE IF NOT EXISTS endereço(
id INT PRIMARY KEY AUTO_INCREMENT,
cep VARCHAR(50) NOT NULL,
logradouro VARCHAR(50) NOT NULL,
numero VARCHAR(10) NOT NULL,
complemento VARCHAR(30) NOT NULL,
bairro VARCHAR(100) NOT NULL

);
