CREATE TABLE IF NOT EXISTS funcionario(
Id INT PRIMARY KEY AUTO_INCREMENT,
NomeCompleto VARCHAR(100) NOT  NULL,
Cpf VARCHAR(14) NOT NULL UNIQUE,
Rg VARCHAR(20) NOT NULL,
DataNascimento DATE,
Genero VARCHAR(20) NOT NULL,
EstadoCivil VARCHAR(20) NOT NULL

);




