CREATE TABLE IF NOT EXISTS funçao(
id INT PRIMARY KEY AUTO_INCREMENT,
cargo VARCHAR(50) NOT NULL,
departamento VARCHAR(60) NOT NULL,
datadeadmissao VARCHAR(50) NOT NULL,
salario VARCHAR(40) NOT NULL

);